# Generated by Smithery. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1

# Build stage
FROM golang:1.25.10-alpine AS builder
WORKDIR /app

# Install Git for potential dependencies and ca-certificates
RUN apk add --no-cache git ca-certificates

# Copy source
COPY go.mod go.sum ./
COPY . .

# Download dependencies and build
RUN go mod download
RUN go build -o mcp-vmanomaly cmd/mcp-vmanomaly/main.go

# Runtime stage
FROM alpine:latest
WORKDIR /app

# Install ca-certificates for HTTPS
RUN apk add --no-cache ca-certificates

# Copy binary from builder
COPY --from=builder /app/mcp-vmanomaly /usr/local/bin/mcp-vmanomaly

# Default entrypoint
ENTRYPOINT ["mcp-vmanomaly"]
